server:
  host: '*'
  port: 5432

logClusters:
  kafkaCluster: !Kafka
    bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS

log: !Kafka
  cluster: kafkaCluster
  topic: !Env XTDB_LOG_TOPIC

storage: !Remote
  objectStore: !S3
    bucket: !Env XTDB_S3_BUCKET
    prefix: "xtdb-object-store"

diskCache:
  path: /var/lib/xtdb/buffers

healthz:
  host: '*'
  port: 8080
