# Use any available port for PGWire Server.
server: 
  port: 0

logClusters:
  kafkaCluster: !Kafka
    bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS

databases:
  xtdb:
    log: !Kafka
      cluster: kafkaCluster
      topic: !Env XTDB_LOG_TOPIC

    storage: !Local
      path: !Env XTDB_STORAGE_DIR

healthz:
  port: !Env XTDB_HEALTHZ_PORT
