server:
  host: '*'
  port: 5432

databases:
  xtdb:
    log: !Local
      path: /var/lib/xtdb/local-log

    storage: !Local
      path: /var/lib/xtdb/local-buffers

healthz:
  host: '*'
  port: 8080
