{
 "title": "XTDB: Node Debugging Dashboard 2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Max"
    }
   ]
  },
  {
   "title": "XTDB - Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions - Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Transactions - Timer (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tx_op_timer_seconds_max{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Transactions - Timer (Quantiles)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "tx_op_timer_seconds{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} - {{quantile}} quantile"
      }
     ]
    }
   ]
  },
  {
   "title": "XTDB - Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query - Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "query_timer_seconds_count{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Query - Timer (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_timer_seconds_max{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Query - Timer",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "query_timer_seconds{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} - {{quantile}} quantile"
      }
     ]
    }
   ]
  },
  {
   "title": "XTDB - JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM - Heap Usage (Average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Heap Usage (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Buffer Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node_id) (jvm_buffer_memory_used_bytes{node_id=\"$xtdbnode\"})",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Live Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Thread States",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} - {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "XTDB - Direct Allocated Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "XTDB - Buffer Pool Allocated Memory",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "memorycache_evictableBytes_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} evictable bytes"
      },
      {
       "expr": "memorycache_freeBytes_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} free bytes"
      },
      {
       "expr": "memorycache_pinnedBytes_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}} pinned bytes"
      }
     ]
    },
    {
     "title": "XTDB - Compactor Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "compactor_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Indexer Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "indexer_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Live Index Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "live_index_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Log Watcher Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "watcher_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
       "legendFormat": "{{node_id}}"
      }
     ]
    }
   ]
  },
  { "title": "XTDB - Memory Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Cache - Record Batch count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "memorycache_metaSliceCount",
     "legendFormat": "{{node_id}} Meta Record Batches"
    },
    {
     "expr": "memorycache_dataSliceCount",
     "legendFormat": "{{node_id}} - Data Record Batches"
    }
   ]
  },
  {
   "title": "Memory Cache - Weights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memorycache_metaWeightBytes_bytes",
     "legendFormat": "{{node_id}} - Meta Record Batches weight"
    },
    {
     "expr": "memorycache_dataWeightBytes_bytes",
     "legendFormat": "{{node_id}} - Data Record Batches weight"
    }
   ]
  },
  {
   "title": "Memory Cache - Pinned vs Unpinned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "memorycache_metaPinned", "legendFormat": "{{node_id}} - Meta pinned" },
    { "expr": "memorycache_metaUnpinned", "legendFormat": "{{node_id}} - Meta unpinned" },
    { "expr": "memorycache_dataPinned", "legendFormat": "{{node_id}} - Data pinned" },
    { "expr": "memorycache_dataUnpinned", "legendFormat": "{{node_id}} - Data unpinned" }
   ]
  },
  {
   "title": "Memory Cache - Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(memory_cache_misses_total[1m])",
     "legendFormat": "{{node_id}} Memory Cache Misses 1min"
    },
    {
     "expr": "rate(disk_cache_misses_total[1m])",
     "legendFormat": "{{node_id}} - Disk Cash Misses 1min"
    },
    {
     "expr": "rate(record_batch_requests_total[1m])",
     "legendFormat": "{{node_id}} - Record Batch Requests 1min"
    },
    {
     "expr": "avg_over_time(rate(memory_cache_misses_total[1m])[5m:])",
     "legendFormat": "{{node_id}} Memory Cache Misses 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    }
   ]
  },
  {
   "title": "Buffer Pool - Record Batch requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(record_batch_requests_total[1m])",
     "legendFormat": "{{node_id}} - Record Batch requests 1min"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch requests 5min avg"
    }
   ]
  }
 ]
}