apiVersion: batch/v1
kind: Job
metadata:
  name: xtdb-cluster-nodes
  namespace: cloud-benchmark
spec:
  parallelism: 3
  completions: 3
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: xtdb-cluster-node
        azure.workload.identity/use: "true"
    spec:
      nodeSelector:
        nodepool: "benchmark"
      serviceAccountName: xtdb-service-account
      restartPolicy: Never
      volumes:
        - name: tmp
          emptyDir: {}
        - name: xtdb-yaml-config
          configMap:
            name: xtdb-yaml-config
        - name: local-disk-cache
          emptyDir:
            sizeLimit: 90Gi
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka.cloud-benchmark.svc.cluster.local 9092; do echo waiting for kafka; sleep 5; done;']
      containers:
        - name: xtdb-node
          image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: xtdb-yaml-config
              mountPath: /var/lib/xtdb-config/xtdbconfig.yaml
              subPath: xtdbconfig.yaml
            - name: local-disk-cache
              mountPath: /var/lib/xtdb/buffers/
          resources:
            requests:
              memory: "8000Mi"
              ephemeral-storage: "100Gi"
            limits:
              memory: "8000Mi"
              ephemeral-storage: "100Gi"
          envFrom:
            - configMapRef:
                name: xtdb-env-config
          env:
            - name: AUCTIONMARK_LOAD_PHASE
              value: "False"
            - name: XTDB_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONFIG_FILE
              value: "/var/lib/xtdb-config/xtdbconfig.yaml"
          ports:
            - name: metrics
              containerPort: 8080
