apiVersion: v1
kind: Service
metadata:
  name: xtdb-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: xtdb-statefulset
spec:
  type: {{ .Values.xtdbService.type }}
  ports:
  - port: {{ .Values.xtdbService.server.servicePort }}
    targetPort: {{ .Values.xtdbService.server.targetPort }}
    name: server
  - port: {{ .Values.xtdbService.healthzServer.servicePort }}
    targetPort: {{ .Values.xtdbService.healthzServer.targetPort }}
    name: healthz
  selector:
    app: xtdb-statefulset
