server:
  host: '*'
  port: 5432

databases:
  xtdb:
    log: !Local
      path: "/var/lib/xtdb/log"

    storage: !Local
      path: "/var/lib/xtdb/buffers"

healthz:
  host: '*'
  port: 8080

modules: 
- !HttpServer
  host: '*'
  port: 3000
